"""
Interactive setup wizard for fetch-job-offers.

Creates the .env file from user input and generates stub files
for cv.md and cover_letter_template.md if they don't exist yet.

Usage:
    uv run python setup.py
"""

import getpass
import sys
from pathlib import Path

BASE_DIR = Path(__file__).parent

_ENV_PATH = BASE_DIR / ".env"
_CV_PATH = BASE_DIR / "cv.md"
_TEMPLATE_PATH = BASE_DIR / "cover_letter_template.md"

_CV_STUB = """\
# Your Name

## Contact
- Email: your.email@example.com
- LinkedIn: linkedin.com/in/yourprofile
- GitHub: github.com/yourusername

## Summary
[Write a 2-3 sentence professional summary here]

## Experience

### Job Title — Company Name (Year – Year)
- [Key achievement or responsibility]
- [Key achievement or responsibility]

## Skills
- **Programming:** Python, SQL, ...
- **ML/AI:** scikit-learn, TensorFlow, ...
- **Tools:** Git, Docker, ...

## Education
### Degree — University (Year)
"""

_TEMPLATE_STUB = """\
Dear Hiring Manager,

[Opening hook: one specific reason you're interested in THIS company — not generic enthusiasm]

[Body paragraph 1: your most relevant experience that directly matches the role's core requirement]

[Body paragraph 2: a second concrete achievement that addresses another key requirement from the job description]

[Closing: confident call to action, specific to the role]

Sincerely,
[Your Name]
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _ask(prompt: str, default: str = "", required: bool = True) -> str:
    """Prompt the user for text input with an optional default value."""
    display = f"{prompt} [{default}]: " if default else f"{prompt}: "
    while True:
        value = input(display).strip()
        if not value and default:
            return default
        if value or not required:
            return value
        print("  ⚠  This field is required.")


def _ask_secret(prompt: str) -> str:
    """Prompt for a secret value (masked input)."""
    while True:
        value = getpass.getpass(f"{prompt}: ").strip()
        if value:
            return value
        print("  ⚠  This field is required.")


def _confirm(prompt: str, default: bool = True) -> bool:
    """Yes/No confirmation prompt."""
    suffix = " [Y/n]: " if default else " [y/N]: "
    answer = input(prompt + suffix).strip().lower()
    if not answer:
        return default
    return answer in ("y", "yes")


def _section(title: str) -> None:
    print(f"\n--- {title} ---")


# ---------------------------------------------------------------------------
# Main wizard
# ---------------------------------------------------------------------------

def main() -> None:
    print()
    print("=" * 54)
    print("  fetch-job-offers — Setup Wizard")
    print("=" * 54)
    print()
    print("This wizard creates your .env file and stub files.")
    print("Your credentials are stored locally only — never shared.")

    # Check for existing .env
    if _ENV_PATH.exists():
        print(f"\n⚠  .env already exists at {_ENV_PATH}")
        if not _confirm("Overwrite it?", default=False):
            print("Setup cancelled.")
            sys.exit(0)

    # --- Gemini ---
    _section("Gemini API")
    print("  Get your free API key at: aistudio.google.com")
    gemini_api_key = _ask_secret("  Gemini API key")
    gemini_model = _ask("  Gemini model", default="gemini-2.5-flash")

    # --- Email ---
    _section("Email (Gmail)")
    print("  Gmail App Password: myaccount.google.com → Security → App Passwords")
    gmail_user = _ask("  Gmail address")
    gmail_app_password = _ask_secret("  Gmail App Password (16 chars, no spaces)")
    recipient_email = _ask("  Send digest to (email)", default=gmail_user)

    # --- Search ---
    _section("LinkedIn Search Preferences")
    search_query = _ask("  Job search query", default="Data Scientist")
    location = _ask("  Location filter (leave empty = worldwide)", required=False)
    max_jobs = _ask("  Max offers per run", default="5")
    hours_old = _ask("  Lookback window in hours", default="24")

    # --- Write .env ---
    _section("Writing .env")
    env_content = f"""\
# fetch-job-offers configuration
# Generated by setup.py — keep this file private, never commit it.

# Gemini API
GEMINI_API_KEY={gemini_api_key}
GEMINI_MODEL={gemini_model}

# Email (Gmail SMTP)
GMAIL_USER={gmail_user}
GMAIL_APP_PASSWORD={gmail_app_password}
RECIPIENT_EMAIL={recipient_email}

# LinkedIn search parameters
SEARCH_QUERY={search_query}
LINKEDIN_LOCATION={location}
MAX_JOBS={max_jobs}
HOURS_OLD={hours_old}
"""
    _ENV_PATH.write_text(env_content, encoding="utf-8")
    print(f"  ✅ .env created at {_ENV_PATH}")

    # --- Stub files ---
    _section("User files")

    if not _CV_PATH.exists():
        _CV_PATH.write_text(_CV_STUB, encoding="utf-8")
        print(f"  ✅ cv.md stub created — edit it with your real CV before running.")
    else:
        print(f"  ✓  cv.md already exists — skipping.")

    if not _TEMPLATE_PATH.exists():
        _TEMPLATE_PATH.write_text(_TEMPLATE_STUB, encoding="utf-8")
        print(f"  ✅ cover_letter_template.md stub created — customize it to your style.")
    else:
        print(f"  ✓  cover_letter_template.md already exists — skipping.")

    # --- Done ---
    print()
    print("=" * 54)
    print("  Setup complete!")
    print("=" * 54)
    print()
    print("Next steps:")
    print("  1. Fill in cv.md with your real CV")
    print("  2. Customize cover_letter_template.md")
    print("  3. Run the pipeline:")
    print("       uv run python main.py")
    print()


if __name__ == "__main__":
    main()
