"""Sends the job digest email via Gmail SMTP."""

import logging
import smtplib
import ssl
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from ..config import settings
from ..models.schemas import DigestItem

logger = logging.getLogger(__name__)

_SEP = "=" * 62
_DASH = "-" * 40


def send_digest(items: list[DigestItem]) -> None:
    """Send the job digest email with all analyses and cover letters."""
    today = date.today().strftime("%Y-%m-%d")
    subject = f"[Job Digest] {len(items)} new Data Scientist offer(s) — {today}"
    body = _build_plaintext_body(items, today)
    _send_email(subject, body)
    logger.info("Digest email sent: %d offer(s).", len(items))


def send_no_jobs_notification() -> None:
    """Send a notification email when no new jobs were found."""
    today = date.today().strftime("%Y-%m-%d")
    subject = f"[Job Digest] No new Data Scientist offers — {today}"
    body = (
        f"No new Data Scientist job offers were found on LinkedIn "
        f"in the last {settings.HOURS_OLD} hours.\n\n"
        f"Date: {today}\n"
        f"Search query: {settings.SEARCH_QUERY}\n"
        f"Location filter: {settings.LINKEDIN_LOCATION or 'worldwide'}\n"
    )
    _send_email(subject, body)
    logger.info("No-jobs notification email sent.")


def _build_plaintext_body(items: list[DigestItem], today: str) -> str:
    lines: list[str] = [
        _SEP,
        f"  DAILY DATA SCIENTIST JOB DIGEST — {today}",
        f"  {len(items)} new offer(s) matching your profile",
        _SEP,
        "",
    ]

    for i, item in enumerate(items, 1):
        job = item["job"]
        lines += [
            f"JOB {i} of {len(items)}",
            f"Title    : {job['title']}",
            f"Company  : {job['company']}",
            f"Location : {job['location']}",
            f"Link     : {job['url']}",
            "",
            _DASH,
            "CV MATCH ANALYSIS",
            _DASH,
            item["analysis"],
            "",
            _DASH,
            "COVER LETTER",
            _DASH,
            item["cover_letter"],
            "",
            _SEP,
            "",
        ]

    lines.append("Generated by fetch-job-offers  —  https://github.com/your-repo")
    return "\n".join(lines)


def _send_email(subject: str, body: str) -> None:
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = settings.GMAIL_USER
    msg["To"] = settings.RECIPIENT_EMAIL
    msg.attach(MIMEText(body, "plain", "utf-8"))

    context = ssl.create_default_context()
    with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
        server.login(settings.GMAIL_USER, settings.GMAIL_APP_PASSWORD)
        server.sendmail(settings.GMAIL_USER, settings.RECIPIENT_EMAIL, msg.as_string())
        logger.debug("SMTP delivery complete.")
